export { COOKIE_NAME, ONE_YEAR_MS } from "@shared/const";

// Generate Microsoft login URL
export const getLoginUrl = () => {
  const redirectUri = `${window.location.origin}/api/oauth/callback`;
  const state = btoa(JSON.stringify({ returnPath: window.location.pathname }));
  
  // This will be generated by the backend
  return `/api/auth/login?state=${encodeURIComponent(state)}`;
};
